before_script: npm install --only=dev
script: npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  keep_history: true
  target_branch: docs
  local_dir: "./docs"
  on:
    branch: master
