language: node_js
node_js:
  - lts/*
before_script: npm install --only=dev
script:
  - npm run lint
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  keep_history: true
  target_branch: gh-pages
  local_dir: "./docs"
  on:
    branch: master
